[package]
name = "rust-book"
version = "0.1.0"
authors = ["Ian Silber ian@isilber.dev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
